# Generated by Django 4.0.6 on 2022-07-21 20:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='aperitivos',
            fields=[
                ('id_aperitivo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('tipo', models.CharField(max_length=25)),
                ('descripcion', models.CharField(max_length=100)),
                ('cantidad_aperitivo', models.PositiveSmallIntegerField()),
                ('precio', models.PositiveIntegerField()),
                ('imagen', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='bebidas',
            fields=[
                ('id_bebidas', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_bebida', models.CharField(max_length=25)),
                ('descripcion', models.CharField(max_length=100)),
                ('tipo', models.CharField(max_length=25)),
                ('tamaño', models.CharField(max_length=15)),
                ('precio', models.PositiveIntegerField()),
                ('imagen', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=50, verbose_name='Apellido')),
                ('telefono', models.PositiveIntegerField()),
                ('email', models.EmailField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='pedido',
            fields=[
                ('id_pedido', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.TimeField()),
                ('precio_subTotal', models.PositiveSmallIntegerField()),
                ('duracion', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='pedido_aperitivo',
            fields=[
                ('id_pedAperitivo', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.PositiveSmallIntegerField()),
                ('aperitivos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Principal.aperitivos')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Principal.pedido')),
            ],
        ),
        migrations.CreateModel(
            name='facturas',
            fields=[
                ('id_facturas', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.TimeField()),
                ('descuento', models.DecimalField(decimal_places=0, max_digits=5)),
                ('forma_pago', models.IntegerField()),
                ('iva', models.DecimalField(decimal_places=0, max_digits=5)),
                ('precio_Total', models.IntegerField()),
                ('Cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Principal.cliente')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Principal.pedido')),
            ],
        ),
        migrations.CreateModel(
            name='bebidas_pedido',
            fields=[
                ('id_pedBebidas', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.PositiveSmallIntegerField()),
                ('bebidas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Principal.bebidas')),
            ],
        ),
    ]
